import { ArticleCategoryKeywordKey } from '../types';

export const mapProductCategoryNameToIdent: {
  [key: string]: ArticleCategoryKeywordKey;
} = {
  'T-Shirts': 'top',
  Trainingsziptop: 'top',
  Trainingssweat: 'top',
  'Trainingsjacke mit durchgehendem RV': 'top',
  'Trainingshose Zwischenlänge': 'bottom',
  'Trainingshose lang': 'bottom',
  'Trainingshose kurz': 'bottom',
  'Torwarthosen (alle Längen)': 'bottom',
  'Torwart Trikots': 'top',
  Polyesterhose: 'bottom',
  Polos: 'top',
  'Outdoor/Freizeitschuhe': 'shoe',
  Kennzeichnungshemden: 'top',
  Jakoletten: 'shoe',
  'Indoor Hosen': 'bottom',
  Hoodies: 'top',
  'Fußballtrikots LA': 'top',
  'Fußballtrikots KA': 'top',
  Fußballsporthosen: 'bottom',
  'Freizeit- und Jogginghose lang': 'bottom',
  'Basic-Sweats / Hoodys': 'top',
  'Basic-/Kapuzen-Jacke': 'top',
  'Allwettersweat/Ziptop': 'top',
  Freizeitanzug: 'tracksuit',
  Polyesteranzug: 'tracksuit',
  'Allwetterjacke (durchgehender RV)': 'top',
  Coachjacke: 'top',
  Fleece: 'top',
  Freizeitjacke: 'top',
  Tanktop: 'top',
  'Sonstige Jacke': 'top',
  'Softshell-Jacken': 'top',
  'Shorts und Röcke': 'bottom',
  'Running und Fitness Tights': 'bottom',
  Polyesterjacke: 'top',
  'Basketball Hosen': 'bottom',
  Basketballtrikots: 'top',
};
